name: Release package to pypi

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Install poetry
      run: |
        pipx install poetry
    - name: Poetry Version
      run: |
        python -V
        poetry --version
    - name: Poetry Install Dependencies
      run: |
        poetry install --no-interaction --without dev,test
    - name: Build
      run: |
        poetry run python -m build
    - name: Publish a Python distribution to PyPI
      if: startsWith(github.event.ref, 'refs/tags') || github.event_name == 'release'
      uses: pypa/gh-action-pypi-publish@release/v1.8
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
