name: Release package to pypi

on:
  release:
    types: [created]


jobs:
  deploy:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/plotly-extend-wrapper
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Install a specific version
      uses: eifinger/setup-rye@v3
      with:
        version: 'latest'
    - name: Install dependencies
      run: rye sync
    - name: Build
      run: rye build
    - name: Publish a Python distribution to PyPI
      if: startsWith(github.event.ref, 'refs/tags') || github.event_name == 'release'
      uses: pypa/gh-action-pypi-publish@release/v1
