name: Unit test

on:
  push:
    branches: [main]

jobs:
  Unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install a specific version
      uses: eifinger/setup-rye@v4
      with:
        version: 'latest'
    - name: Install dependencies
      run: rye sync
    - name: Test
      run: |
        rye run pytest test --cov=./plotly_extend_wrapper --cov-report=xml
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
