name: Unit test

on:
  push:
    branches:
      - main
      - surface

jobs:
  Unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Install poetry
      run: |
        pipx install poetry
    - name: Poetry Version
      run: |
        python -V
        poetry --version
    - name: Poetry Install Dependencies
      run: |
        poetry install --no-interaction --without dev,deploy
    - name: Test
      run: |
        poetry run pytest test --cov=./plotly_extend_wrapper --cov-report=xml
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
